name: Release Addon

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ADDON_NAME: ClassHUD

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine version information
        id: version
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME#v}"
          ZIP_NAME="${ADDON_NAME}-${TAG_NAME}.zip"

          echo "tag_name=${TAG_NAME}" >> "$GITHUB_OUTPUT"
          echo "addon_version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "zip_name=${ZIP_NAME}" >> "$GITHUB_OUTPUT"

      - name: Inject version into TOC
        run: |
          sed -i "s/@project-version@/${{ steps.version.outputs.addon_version }}/" ClassHUD.toc

      - name: Package addon
        run: |
          mkdir -p build/${ADDON_NAME}
          rsync -a \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='build/' \
            ./ build/${ADDON_NAME}/
          cd build
          zip -r "../${{ steps.version.outputs.zip_name }}" "${ADDON_NAME}"

      - name: Create or update GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          files: ${{ steps.version.outputs.zip_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
